[book]
authors = ["piper"]
language = "en"
multilingual = false
src = "src"
title = "sentio中文开发文档"


[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/piperTang/sentio-chinese-docs"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true
