[book]
authors = ["piper"]
language = "em"
multilingual = false
src = "src"
title = "sentio-chinese-docs"


[output.html]
site-url = "/sentio-chinese-docs/"
git-repository-url = "https://pipertang.github.io/sentio-chinese-docs"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true